### ISSUE TITLE
Vdash shows GETs were PUTs are expected

### ISSUE THREAD

**Issue by willief** [happybeing/vdash#11]
DRAFT  :   When PUTing files to the local baby-fleming network I see indications in the GETs row but nothing under PUT.

**Comment by happybeing** [comment]
Vdash is looking for indications of PUT and GET in the logfile so what you see reflects: 

1. what I've chosen to count as PUT and GET which may be misleading
2. when those messages are logged by `sn_node`

I wouldn't be surprised to find the messages I've chosen aren't ideal, but they are the best I could find. I think once the MaidSafe team have a bit more bandwidth we can discuss with them what is available in the logs and how best to use it, and whether they can improve this to make the log output (and `vdash` metrics) more useful.

For now let's keep an eye on things and use this issue as a placeholder until someone (ideally not me because I don't have much time for code) takes this up with the team. 

Maybe @Thierry61 (who is doing similar processing with https://github.com/Thierry61/sn_node_dash) will also be interested or able to suggest improvements either to what `vdash` counts or the messages logged by `sn_node`?

**Comment by willief** [comment]
screenshot just cos I took one  while doing a large recursive PUT

![image](https://user-images.githubusercontent.com/293741/158431143-b9f0f36e-6a84-4487-af7d-0d96e470a704.png)

**Comment by willief** [comment]
Yes, I'm not expecting instant fixes for these issues, think of them as
placeholders/reminders

**Comment by Thierry61** [comment]
FWIW I'm also looking for "Getting chunk" and "StoredNewChunk" in sn_node_dash and I get both many Gets and many Puts during a recursive safe files put command.

@happybeing, what's is interesting in the code you referenced is that you also detect "Editing Register success!" which I didn't. I will do the same and integrate them as "Edits".
