### ISSUE TITLE
NanoTokens -> AttoTokens with recent transition EVM payments

### ISSUE THREAD

**Issue by grumbach** [happybeing/vdash#32]
Hey Happybeing, 
With the recent transition to EVM based payments, tokens will have more decimals. 
- from: nano 10^-9
- to: atto 10^-18

The log line read by vdash below, was changed accordingly to match the new unit. 

```diff
-        info!("Total payment of {storecost:?} nanos accepted for record {pretty_key}");
+        info!("Total payment of {storecost:?} atto tokens accepted for record {pretty_key}");
```

Just PRd this in here: https://github.com/maidsafe/safe_network/pull/2236

**Comment by happybeing** [comment]
@grumbach Thanks for the heads-up. Can you tell me how this affects the values - as in is the smallest chargeable unit (previously 1 nano) now 10^-18 instead of 10^-9?

That's implied obviously, but it appears to make things less compatible with the native token, as well as a very much larger number of 'units' per single token. So I'm also curious about the reason for the change! :smile:

**Comment by grumbach** [comment]
The reason is that we're going to use an ERC20 token and amounts in Ethereum land have 18 decimals. So instead of nanos we'll be using attos. 
When going back to the native token, we'll have to decide wether we want to go back to 9 decimals or keep the 18 decimals system. This hasn't been decided yet but is an excellent question!

**Comment by happybeing** [comment]
Closing with relevant mods in https://github.com/happybeing/vdash/commit/f5402fc7cf4ef5691addad090a7f8fd8f295194b and vdash v0.18.0
